### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 0.5

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
Opening this PR mainly to ask if it is worth setting the app as working 😬

**Comment by tituspijean** [comment]
I guess so? There are still the TURN server and transfer of encryption keys from Synapse though.

**Comment by ericgaspar** [comment]
As for TURN, the external package can be used.

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Pull request merged**
