### PR TITLE
Fix #50

### LINKED ISSUE #50: All sessions IP addresses are localhost
### Describe the bug

All sessions appear to be coming from localhost addresses (`127.0.0.1`, `::1`). It blocks a means for verifying sessions with their IP address.

### Context

- Hardware: vps
- YunoHost version: 11.
- I have access to my server: ssh and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 0.9.5~ynh1

### Expected behavior

I guess the NGINX proxy location should pass along the real client IP.

### Logs

image

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #50*

## Solution

- *`more_set_headers "X-Real-IP: $remote_addr";`*
- *Apply last example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by tituspijean** [comment]
The "fix: is still not fixing anything. :)

**Comment by yalh76** [comment]
The sessions don't go through nginx ?
I though adding `more_set_headers "X-Real-IP: $remote_addr"` would send to dendrite the real IP address

**Comment by tituspijean** [comment]
It was missing a configuration key! (How about I read the doc from time to time? 😅 )

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
aaaand it's not working. IP addresses are still displayed as `127.0.0.1` or `::1`.

**Comment by yalh76** [comment]
> It was missing a configuration key! (How about I read the doc from time to time? 😅 )

I first planned to solve the issue => https://github.com/YunoHost-Apps/dendrite_ynh/pull/59/commits/a7f20354b2d821cd93d8fe6220863d24164a5756

and then I though applying example_ynh wouldn't be bad ^^

**Comment by yalh76** [comment]
> aaaand it's not working. IP addresses are still displayed as `127.0.0.1` or `::1`.

as written in https://github.com/matrix-org/dendrite/blob/main/docs/nginx/monolith-sample.conf, maybe we need `more_set_headers "Host: $host";` you removed at https://github.com/YunoHost-Apps/dendrite_ynh/pull/59/commits/e65d7e64ecd9f95968b88b106d07ab7f412d3e86

**Comment by tituspijean** [comment]
For some weird reason, only `proxy_set_header` works, not `more_set_headers`. I added the Host one too for good measure.

**Comment by tituspijean** [comment]
!testme

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
