### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jahway603**
Updated README.md to indicate dendrite is beta software, as per the [upstream README.md](https://github.com/matrix-org/dendrite/blob/main/README.md)

## Problem

- Dendrite is not alpha software anymore, but is now beta software, so users and potential users need to know this.

## Solution

- Update README.md to indicate dendrite is beta software, as per the [upstream README.md](https://github.com/matrix-org/dendrite/blob/main/README.md)

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

N/A

### CODE REVIEW

**Comment by jahway603** [comment]
@tituspijean the yunohost-bot reverted this PR as you can see in [this commit](https://github.com/YunoHost-Apps/dendrite_ynh/commit/296f1ca2265f7fd2f8dd79cc6eee61fd2ef17da1). How to fix?

**Comment by tituspijean** [comment]
OK see. This bit actually comes from the antifeatures, stored in the catalog over at YunoHost/apps/apps.toml

I think we should fix the description upstream, to include both alpha and beta software.

**Comment by jahway603** [comment]
@tituspijean I'd like to understand where changes like this should be submitted to.

**Comment by tituspijean** [comment]
You can read the README of the repository I mentioned.

**Pull request merged**
