### PR TITLE
Make the app work

### LINKED ISSUE #1: Initial to-do list
# To-do list before marking the app as working.

YunoHost scripts:
- [x] Upgrade
- [x] Backup and restore
- [x] Change URL
- [x] ~~Fix SSO login for Element~~ (not yet implemented by Matrix, let's use a config panel)

Dendrite features:
- ~~TURN server (reuse what Synapse does?, package a global TURN server for YunoHost?)~~ not needed anymore?
- ~~(optional) Offer to reuse encryption key from Synapse (https://github.com/matrix-org/dendrite/blob/master/docs/serverkeyformat.md). That's important to avoid that irritating `(@user:server.tld)` addendum after the username when the same username is used twice in one room.~~ seems not to be an issue

Feel free to create dedicated issues if some tasks require brainstorming/assistance.

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem
- The app is yet to be fully functional 

## Solution
- Closes #1 

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
The CI is happy now (except for the `inprogress` in apps catalog). Though we need to be careful since I had to manually make NGINX return a `200` code on the "landing" page.

**Comment by tituspijean** [comment]
- [ ] Make the app public by default
- [ ] Integrate the SSO login

**Review by alexAubin — APPROVED** [review]
(LGTM so far i guess but super super quick review)

**Comment by tituspijean** [comment]
I am still not satisfied by its state. Like we still do not have the SSO, the STUN/TURN server, retrieval of the Synapse encryption key if the user wants to migrate, etc. 😇

**Comment by alexAubin** [comment]
Randomly re-reading this

Wouldn't it make sense to just merge this already anyway, so that it allow for easier testing for people who may want to develop / iterate on this app ? (Considering the app is still flagged "inprogress" anyway)

**Review by ericgaspar — APPROVED** [review]

**Comment by tituspijean** [comment]
Let's do this then!

**Pull request merged**
